# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: astro.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='astro.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61stro.proto\"\x15\n\x13ReqStartCalibration\"\x14\n\x12ReqStopCalibration\":\n\nReqGotoDSO\x12\n\n\x02ra\x18\x01 \x01(\x01\x12\x0b\n\x03\x64\x65\x63\x18\x02 \x01(\x01\x12\x13\n\x0btarget_name\x18\x03 \x01(\t\"R\n\x12ReqGotoSolarSystem\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x13\n\x0btarget_name\x18\x04 \x01(\t\"\r\n\x0bReqStopGoto\"\x1b\n\x19ReqCaptureRawLiveStacking\"\x1f\n\x1dReqStopCaptureRawLiveStacking\"\x13\n\x11ReqCheckDarkFrame\"3\n\x11ResCheckDarkFrame\x12\x10\n\x08progress\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"&\n\x13ReqCaptureDarkFrame\x12\x0f\n\x07reshoot\x18\x01 \x01(\x05\"\x19\n\x17ReqStopCaptureDarkFrame\"\x0b\n\tReqGoLive\"@\n\x15ReqTrackSpecialTarget\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0b\n\x03lat\x18\x03 \x01(\x01\"\x1b\n\x19ReqStopTrackSpecialTargetb\x06proto3'
)




_REQSTARTCALIBRATION = _descriptor.Descriptor(
  name='ReqStartCalibration',
  full_name='ReqStartCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=36,
)


_REQSTOPCALIBRATION = _descriptor.Descriptor(
  name='ReqStopCalibration',
  full_name='ReqStopCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=58,
)


_REQGOTODSO = _descriptor.Descriptor(
  name='ReqGotoDSO',
  full_name='ReqGotoDSO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='ReqGotoDSO.ra', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dec', full_name='ReqGotoDSO.dec', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_name', full_name='ReqGotoDSO.target_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=118,
)


_REQGOTOSOLARSYSTEM = _descriptor.Descriptor(
  name='ReqGotoSolarSystem',
  full_name='ReqGotoSolarSystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='ReqGotoSolarSystem.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon', full_name='ReqGotoSolarSystem.lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='ReqGotoSolarSystem.lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_name', full_name='ReqGotoSolarSystem.target_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=202,
)


_REQSTOPGOTO = _descriptor.Descriptor(
  name='ReqStopGoto',
  full_name='ReqStopGoto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=217,
)


_REQCAPTURERAWLIVESTACKING = _descriptor.Descriptor(
  name='ReqCaptureRawLiveStacking',
  full_name='ReqCaptureRawLiveStacking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=246,
)


_REQSTOPCAPTURERAWLIVESTACKING = _descriptor.Descriptor(
  name='ReqStopCaptureRawLiveStacking',
  full_name='ReqStopCaptureRawLiveStacking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=279,
)


_REQCHECKDARKFRAME = _descriptor.Descriptor(
  name='ReqCheckDarkFrame',
  full_name='ReqCheckDarkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=300,
)


_RESCHECKDARKFRAME = _descriptor.Descriptor(
  name='ResCheckDarkFrame',
  full_name='ResCheckDarkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='ResCheckDarkFrame.progress', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ResCheckDarkFrame.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=353,
)


_REQCAPTUREDARKFRAME = _descriptor.Descriptor(
  name='ReqCaptureDarkFrame',
  full_name='ReqCaptureDarkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reshoot', full_name='ReqCaptureDarkFrame.reshoot', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=393,
)


_REQSTOPCAPTUREDARKFRAME = _descriptor.Descriptor(
  name='ReqStopCaptureDarkFrame',
  full_name='ReqStopCaptureDarkFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=420,
)


_REQGOLIVE = _descriptor.Descriptor(
  name='ReqGoLive',
  full_name='ReqGoLive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=433,
)


_REQTRACKSPECIALTARGET = _descriptor.Descriptor(
  name='ReqTrackSpecialTarget',
  full_name='ReqTrackSpecialTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='ReqTrackSpecialTarget.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon', full_name='ReqTrackSpecialTarget.lon', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='ReqTrackSpecialTarget.lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=499,
)


_REQSTOPTRACKSPECIALTARGET = _descriptor.Descriptor(
  name='ReqStopTrackSpecialTarget',
  full_name='ReqStopTrackSpecialTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=528,
)

DESCRIPTOR.message_types_by_name['ReqStartCalibration'] = _REQSTARTCALIBRATION
DESCRIPTOR.message_types_by_name['ReqStopCalibration'] = _REQSTOPCALIBRATION
DESCRIPTOR.message_types_by_name['ReqGotoDSO'] = _REQGOTODSO
DESCRIPTOR.message_types_by_name['ReqGotoSolarSystem'] = _REQGOTOSOLARSYSTEM
DESCRIPTOR.message_types_by_name['ReqStopGoto'] = _REQSTOPGOTO
DESCRIPTOR.message_types_by_name['ReqCaptureRawLiveStacking'] = _REQCAPTURERAWLIVESTACKING
DESCRIPTOR.message_types_by_name['ReqStopCaptureRawLiveStacking'] = _REQSTOPCAPTURERAWLIVESTACKING
DESCRIPTOR.message_types_by_name['ReqCheckDarkFrame'] = _REQCHECKDARKFRAME
DESCRIPTOR.message_types_by_name['ResCheckDarkFrame'] = _RESCHECKDARKFRAME
DESCRIPTOR.message_types_by_name['ReqCaptureDarkFrame'] = _REQCAPTUREDARKFRAME
DESCRIPTOR.message_types_by_name['ReqStopCaptureDarkFrame'] = _REQSTOPCAPTUREDARKFRAME
DESCRIPTOR.message_types_by_name['ReqGoLive'] = _REQGOLIVE
DESCRIPTOR.message_types_by_name['ReqTrackSpecialTarget'] = _REQTRACKSPECIALTARGET
DESCRIPTOR.message_types_by_name['ReqStopTrackSpecialTarget'] = _REQSTOPTRACKSPECIALTARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqStartCalibration = _reflection.GeneratedProtocolMessageType('ReqStartCalibration', (_message.Message,), {
  'DESCRIPTOR' : _REQSTARTCALIBRATION,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStartCalibration)
  })
_sym_db.RegisterMessage(ReqStartCalibration)

ReqStopCalibration = _reflection.GeneratedProtocolMessageType('ReqStopCalibration', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPCALIBRATION,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopCalibration)
  })
_sym_db.RegisterMessage(ReqStopCalibration)

ReqGotoDSO = _reflection.GeneratedProtocolMessageType('ReqGotoDSO', (_message.Message,), {
  'DESCRIPTOR' : _REQGOTODSO,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqGotoDSO)
  })
_sym_db.RegisterMessage(ReqGotoDSO)

ReqGotoSolarSystem = _reflection.GeneratedProtocolMessageType('ReqGotoSolarSystem', (_message.Message,), {
  'DESCRIPTOR' : _REQGOTOSOLARSYSTEM,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqGotoSolarSystem)
  })
_sym_db.RegisterMessage(ReqGotoSolarSystem)

ReqStopGoto = _reflection.GeneratedProtocolMessageType('ReqStopGoto', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPGOTO,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopGoto)
  })
_sym_db.RegisterMessage(ReqStopGoto)

ReqCaptureRawLiveStacking = _reflection.GeneratedProtocolMessageType('ReqCaptureRawLiveStacking', (_message.Message,), {
  'DESCRIPTOR' : _REQCAPTURERAWLIVESTACKING,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqCaptureRawLiveStacking)
  })
_sym_db.RegisterMessage(ReqCaptureRawLiveStacking)

ReqStopCaptureRawLiveStacking = _reflection.GeneratedProtocolMessageType('ReqStopCaptureRawLiveStacking', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPCAPTURERAWLIVESTACKING,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopCaptureRawLiveStacking)
  })
_sym_db.RegisterMessage(ReqStopCaptureRawLiveStacking)

ReqCheckDarkFrame = _reflection.GeneratedProtocolMessageType('ReqCheckDarkFrame', (_message.Message,), {
  'DESCRIPTOR' : _REQCHECKDARKFRAME,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqCheckDarkFrame)
  })
_sym_db.RegisterMessage(ReqCheckDarkFrame)

ResCheckDarkFrame = _reflection.GeneratedProtocolMessageType('ResCheckDarkFrame', (_message.Message,), {
  'DESCRIPTOR' : _RESCHECKDARKFRAME,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ResCheckDarkFrame)
  })
_sym_db.RegisterMessage(ResCheckDarkFrame)

ReqCaptureDarkFrame = _reflection.GeneratedProtocolMessageType('ReqCaptureDarkFrame', (_message.Message,), {
  'DESCRIPTOR' : _REQCAPTUREDARKFRAME,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqCaptureDarkFrame)
  })
_sym_db.RegisterMessage(ReqCaptureDarkFrame)

ReqStopCaptureDarkFrame = _reflection.GeneratedProtocolMessageType('ReqStopCaptureDarkFrame', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPCAPTUREDARKFRAME,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopCaptureDarkFrame)
  })
_sym_db.RegisterMessage(ReqStopCaptureDarkFrame)

ReqGoLive = _reflection.GeneratedProtocolMessageType('ReqGoLive', (_message.Message,), {
  'DESCRIPTOR' : _REQGOLIVE,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqGoLive)
  })
_sym_db.RegisterMessage(ReqGoLive)

ReqTrackSpecialTarget = _reflection.GeneratedProtocolMessageType('ReqTrackSpecialTarget', (_message.Message,), {
  'DESCRIPTOR' : _REQTRACKSPECIALTARGET,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqTrackSpecialTarget)
  })
_sym_db.RegisterMessage(ReqTrackSpecialTarget)

ReqStopTrackSpecialTarget = _reflection.GeneratedProtocolMessageType('ReqStopTrackSpecialTarget', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPTRACKSPECIALTARGET,
  '__module__' : 'astro_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopTrackSpecialTarget)
  })
_sym_db.RegisterMessage(ReqStopTrackSpecialTarget)


# @@protoc_insertion_point(module_scope)
