# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csystem.proto\"\x1f\n\nReqSetTime\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"\"\n\x0eReqSetTimezone\x12\x10\n\x08timezone\x18\x01 \x01(\t\"\x1d\n\rReqSetMtpMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"\x1d\n\rReqSetCpuMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\x62\x06proto3'
)




_REQSETTIME = _descriptor.Descriptor(
  name='ReqSetTime',
  full_name='ReqSetTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ReqSetTime.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=47,
)


_REQSETTIMEZONE = _descriptor.Descriptor(
  name='ReqSetTimezone',
  full_name='ReqSetTimezone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timezone', full_name='ReqSetTimezone.timezone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=83,
)


_REQSETMTPMODE = _descriptor.Descriptor(
  name='ReqSetMtpMode',
  full_name='ReqSetMtpMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ReqSetMtpMode.mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=114,
)


_REQSETCPUMODE = _descriptor.Descriptor(
  name='ReqSetCpuMode',
  full_name='ReqSetCpuMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ReqSetCpuMode.mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['ReqSetTime'] = _REQSETTIME
DESCRIPTOR.message_types_by_name['ReqSetTimezone'] = _REQSETTIMEZONE
DESCRIPTOR.message_types_by_name['ReqSetMtpMode'] = _REQSETMTPMODE
DESCRIPTOR.message_types_by_name['ReqSetCpuMode'] = _REQSETCPUMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSetTime = _reflection.GeneratedProtocolMessageType('ReqSetTime', (_message.Message,), {
  'DESCRIPTOR' : _REQSETTIME,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:ReqSetTime)
  })
_sym_db.RegisterMessage(ReqSetTime)

ReqSetTimezone = _reflection.GeneratedProtocolMessageType('ReqSetTimezone', (_message.Message,), {
  'DESCRIPTOR' : _REQSETTIMEZONE,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:ReqSetTimezone)
  })
_sym_db.RegisterMessage(ReqSetTimezone)

ReqSetMtpMode = _reflection.GeneratedProtocolMessageType('ReqSetMtpMode', (_message.Message,), {
  'DESCRIPTOR' : _REQSETMTPMODE,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:ReqSetMtpMode)
  })
_sym_db.RegisterMessage(ReqSetMtpMode)

ReqSetCpuMode = _reflection.GeneratedProtocolMessageType('ReqSetCpuMode', (_message.Message,), {
  'DESCRIPTOR' : _REQSETCPUMODE,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:ReqSetCpuMode)
  })
_sym_db.RegisterMessage(ReqSetCpuMode)


# @@protoc_insertion_point(module_scope)
